# Домашнее задание №5

### Задание №1 (1,5 балла)

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [1]:
import numpy as np

arr_1 = np.array([2, 4, 6, 8, 10, 12])
arr_2 = np.array([7, 11, 15, 18, 23, 29])
arr_3 = (arr_1 + arr_2)**2
print(arr_3)

[  81  225  441  676 1089 1681]


$2.$ Выведите все элементы из первого массива, которые стоят на тех местах, где элементы второго массива больше 12 и дают остаток 3 при делении на 5.

In [2]:
print(arr_1[np.logical_and(arr_2 > 12, arr_2 % 5 == 3)])

[ 8 10]


*3.* Для первого массива найдите остатки от деления на 2, а для второго --- на 3. Для каждого получившегося массива выведите его уникальные значения (см. семинар).

In [3]:
arr_1_un = np.unique(arr_1 % 2)
arr_2_un = np.unique(arr_2 % 3)
print(arr_1_un, arr_2_un)

[0] [0 1 2]


### Задание №2 (1,5 балла)

Найдите интересный для вас датасет. Например, можно выбрать датасет [тут](http://data.un.org/Explorer.aspx) или [тут](https://hls.harvard.edu/library/research/find-a-database/). Если выскакивают ошибки при считывании таблицы, попробуйте их погуглить и решить проблему!

1. Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
2. Проанализируйте и прокомментируйте содержательно получившиеся результаты
    - недостаточно написать фразы формата "Средний возраст = 60, а минимальный = 20", следует дать пояснение, что это значит и какие выводы можно сделать в рамках датасета
3. Все комментарии оформляйте строго в ячейках формата Markdown
    - для этого надо в выпадающем окошке сверху для текущей ячейки сменить тип Code на Markdown
    ![](https://i.imgur.com/vl7Fmg9.png)

In [18]:
data = np.loadtxt("Intentional homicide victims by counts and rates p.txt", dtype=int)
print(data)

[[2000 2001 2002 ... 2016 2017 2018]
 [   0    1    1 ...    6    6    6]
 [ 131  220  216 ...    2    2    2]
 ...
 [ 697    1    1 ...    1    1    0]
 [ 797    1    1 ...    1    1    0]
 [   0 1529 1623 ...    1    1    0]]


Среднее количество убийств в <b>2007</b> году

In [25]:
np.mean(data[:, 7])

1235.7541666666666

Максимальное количество убийств за <b>все</b> время

In [24]:
np.max(data[1:,:])

64201