In [1]:
import numpy as np

# Домашнее задание на повторение numpy
В задании все пункты необходимо выполнить с помощью numpy, без использования циклов/map/и тд! 

Задание выполняется __самостоятельно__. Категорически запрещено пользоваться чужими решениями заданий (даже смотреть их), в том числе, размещенными в открытых источниках (если таковые обнаружатся). При обнаружении списывания выставляется 0 за задание (в случае списывания у одногруппника/однокурскника - __ему/ей тоже__), а также подается докладная записка в учебный офис. Проверка на списывание проводится и автоматическими средствами, и вручную.

### История

В конце каждого семестра каждый семинарист сталкивается с необходимостью выставить студентам накопленную в семестре оценку. Часто семинаристы делают это с помощью Excel или GoogleSheets, но поверьте, с этим возникают проблемы. В задании вам надо помочь семинаристу некоторого курса выполнить эту непростую работу с помощью numpy :)

Выполните ячейку ниже, чтобы загрузить данные и визуально проверить корректность их считывания.

По строкам - студенты, по столбцам - их оценки. В курсе семинарист провел три проверочных (первые три колонки), выдал три домашних работы (следующие три колонки), кроме того, у студентов есть оценка за коллоквиум (последняя колонка).

In [2]:
marks = np.loadtxt("https://raw.githubusercontent.com/nadiinchi/iad2019/master/materials/data_hw1.txt")

In [3]:
marks[:3]

array([[ 7. ,  8. , 10. ,  0. ,  0. ,  2.1,  1.5],
       [ 0. ,  6. ,  4.4,  4. ,  0. ,  5. ,  4.3],
       [ 3. ,  7. ,  8.7,  7.6,  7. ,  9.7, 10. ]])

### Число студентов (1 балл)
Сколько студентов в группе семинариста?

In [4]:
# Записать ответ в переменную num_studs
num_studs = marks.shape[0] 

In [5]:
print(num_studs)

28


### Очень сложная проверочная, или просто добрый семинарист (1.5 балла)
Семинарист помнит, что первая проверочная получилась очень сложной, и максимальный балл в группе был далеко не 10. Поэтому он решил перенормировать баллы за эту проверочную на максимум по группе (поделить на максимум и умножить на 10) - чтобы у студента с максимальной оценкой получилось 10, а у остальных - просто оценка больше.

Каков максимальный балл за первую проверочную?

In [6]:
# Записать ответ в переменную max_mark
max_mark = marks.max(axis = 0)

In [7]:
print(max_mark)

[ 7.  10.  10.  10.5 10.7 10.  10. ]


Разделите первый столбец на max_mark (для этого надо выделить столбец, поставить после соответствующего выражения знак = и присвоить новое значение столбца)

In [8]:
marks[:,0] = np.round((marks[:, 0]/max_mark[0]) * 10, 2)

In [9]:
print(marks)

[[10.    8.   10.    0.    0.    2.1   1.5 ]
 [ 0.    6.    4.4   4.    0.    5.    4.3 ]
 [ 4.29  7.    8.7   7.6   7.    9.7  10.  ]
 [ 4.86  1.3   7.    3.4   0.    9.4   9.  ]
 [ 9.71  9.1   8.2   0.    0.    7.9   7.9 ]
 [10.   10.   10.    9.    9.5  10.    8.  ]
 [ 8.57 10.    9.7   8.7   7.    8.5   9.7 ]
 [ 0.    9.3   5.7   0.    0.    0.    0.  ]
 [ 7.14 10.   10.    9.9  10.5  10.    9.  ]
 [ 0.    8.7   8.    9.7  10.    9.5  10.  ]
 [ 4.29  6.9   7.9   0.    0.    0.    0.  ]
 [ 5.71 10.   10.    9.9   9.7  10.    9.  ]
 [ 0.    0.    0.    0.    0.    0.    0.  ]
 [ 8.57  5.   10.    9.7  10.   10.    8.  ]
 [ 7.14 10.    9.    7.    7.9  10.    9.  ]
 [ 0.    6.    7.4   0.    0.    0.    0.  ]
 [10.   10.   10.    9.7  10.   10.   10.  ]
 [ 6.43  8.7  10.    9.5   0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    5.6   8.7   0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.  ]
 [ 8.57 10.   10.    9.7   7.   10.    7.  ]
 [ 9.29  8

### Подсчет накопленной оценки (1.5 балла)
Для вычисления накопленной надо посчитать средние оценки за проверочные для каждого студента и средние за домашние работы (может пригодиться np.mean). Накопленная оценка есть 0.3\*Проверочные + 0.4\*Домашние + 0.3\*Коллоквиум. Вычислите накопленные оценки и добавьте их в последний столбец матрицы (нужно добавить еще один новый столбец).

In [10]:
# Веса следует брать из переменной weights, а не вписывать вручную
weights = [0.3, 0.4, 0.3]

In [11]:
end_a = marks[:, 0:3] * weights[0]
end_b = marks[:, 3:6] * weights[1]
end_c = marks[:, 6:7] * weights[2]

In [12]:
end_a = np.mean(end_a, axis = 1, keepdims = 1)
end_b = np.mean(end_b, axis = 1, keepdims = 1)

In [13]:
end_tabl = np.round(end_a + end_b + end_c, 2)
marks = np.hstack((marks,end_tabl))
print(marks)

[[10.    8.   10.    0.    0.    2.1   1.5   3.53]
 [ 0.    6.    4.4   4.    0.    5.    4.3   3.53]
 [ 4.29  7.    8.7   7.6   7.    9.7  10.    8.24]
 [ 4.86  1.3   7.    3.4   0.    9.4   9.    5.72]
 [ 9.71  9.1   8.2   0.    0.    7.9   7.9   6.12]
 [10.   10.   10.    9.    9.5  10.    8.    9.2 ]
 [ 8.57 10.    9.7   8.7   7.    8.5   9.7   8.96]
 [ 0.    9.3   5.7   0.    0.    0.    0.    1.5 ]
 [ 7.14 10.   10.    9.9  10.5  10.    9.    9.47]
 [ 0.    8.7   8.    9.7  10.    9.5  10.    8.56]
 [ 4.29  6.9   7.9   0.    0.    0.    0.    1.91]
 [ 5.71 10.   10.    9.9   9.7  10.    9.    9.22]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 8.57  5.   10.    9.7  10.   10.    8.    8.72]
 [ 7.14 10.    9.    7.    7.9  10.    9.    8.63]
 [ 0.    6.    7.4   0.    0.    0.    0.    1.34]
 [10.   10.   10.    9.7  10.   10.   10.    9.96]
 [ 6.43  8.7  10.    9.5   0.    0.    0.    3.78]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    5.6   8.7   0.    0.  

### Студенты, которых, вероятно, отчислят (1.5 балла)

Сколько в группе студентов с накопленной оценкой 0? Вам может понадобиться тот факт, что применение np.sum к бинарному вектору дает число значений True в нем, например:

In [14]:
np.sum([True, False, True]) # 2 значения True

2

Также обратим внимание на операцию поэлементного сравнения, возвращающую массив из True и False:

In [15]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 3])
print(a == b)
print(a > b)

[False False  True]
[False False False]


In [16]:
zero_table = marks[:, -1] == 0

In [17]:
zero_table = np.sum(zero_table)

In [18]:
print(zero_table)

3


### Студенты, которые получат автоматы (1.5 балла)
Автомат получат студенты, у которых накопленная оценка больше 7. Добавьте еще один столбец - в нем стоит 1, если студент получает автомат, и 0 иначе.

In [21]:
aut_marks = marks[:, 7:8] > 7

In [22]:
marks = np.hstack((marks, aut_marks))

In [23]:
print(marks)

[[10.    8.   10.    0.    0.    2.1   1.5   3.53  0.  ]
 [ 0.    6.    4.4   4.    0.    5.    4.3   3.53  0.  ]
 [ 4.29  7.    8.7   7.6   7.    9.7  10.    8.24  1.  ]
 [ 4.86  1.3   7.    3.4   0.    9.4   9.    5.72  0.  ]
 [ 9.71  9.1   8.2   0.    0.    7.9   7.9   6.12  0.  ]
 [10.   10.   10.    9.    9.5  10.    8.    9.2   1.  ]
 [ 8.57 10.    9.7   8.7   7.    8.5   9.7   8.96  1.  ]
 [ 0.    9.3   5.7   0.    0.    0.    0.    1.5   0.  ]
 [ 7.14 10.   10.    9.9  10.5  10.    9.    9.47  1.  ]
 [ 0.    8.7   8.    9.7  10.    9.5  10.    8.56  1.  ]
 [ 4.29  6.9   7.9   0.    0.    0.    0.    1.91  0.  ]
 [ 5.71 10.   10.    9.9   9.7  10.    9.    9.22  1.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 8.57  5.   10.    9.7  10.   10.    8.    8.72  1.  ]
 [ 7.14 10.    9.    7.    7.9  10.    9.    8.63  1.  ]
 [ 0.    6.    7.4   0.    0.    0.    0.    1.34  0.  ]
 [10.   10.   10.    9.7  10.   10.   10.    9.96  1.  ]
 [ 6.43  8.7  10.    9.5   0.  

### Студенты, которые будут освобождены от задач на экзамене (1.5 балла)
Семинарист решил, что первая половина группы в рейтинге по накопленной оценке будет освобождена от решения задач на экзамене. Выделите этих студентов в отдельный массив. Для этого надо отсортировать строки массива (np.argsort) и взять первую половину.

In [31]:
sort = np.argsort(marks, axis = 0)

In [32]:
sorted_marks = marks[sort[:, 7:8], :]

In [33]:
sorted_marks = sorted_marks[sorted_marks.shape[0]//2:, :]

In [34]:
print(sorted_marks)

[[[ 4.29  7.    8.7   7.6   7.    9.7  10.    8.24  1.  ]]

 [[ 8.57 10.   10.    9.7   7.   10.    7.    8.52  1.  ]]

 [[ 0.    8.7   8.    9.7  10.    9.5  10.    8.56  1.  ]]

 [[ 7.14 10.    9.    7.    7.9  10.    9.    8.63  1.  ]]

 [[ 8.57  5.   10.    9.7  10.   10.    8.    8.72  1.  ]]

 [[ 5.    9.3  10.    9.9  10.   10.    8.    8.82  1.  ]]

 [[ 8.57 10.    9.7   8.7   7.    8.5   9.7   8.96  1.  ]]

 [[ 4.29  8.7  10.    9.4  10.7  10.    9.    9.01  1.  ]]

 [[10.   10.   10.    9.    9.5  10.    8.    9.2   1.  ]]

 [[ 5.71 10.   10.    9.9   9.7  10.    9.    9.22  1.  ]]

 [[ 7.14 10.   10.    9.9  10.5  10.    9.    9.47  1.  ]]

 [[10.    9.7  10.    8.1  10.   10.    9.5   9.57  1.  ]]

 [[ 9.29  8.7   9.5  10.5   9.8  10.   10.    9.79  1.  ]]

 [[10.   10.   10.    9.7  10.   10.   10.    9.96  1.  ]]]
